### ISSUE TITLE
Save photo with the square of the face recognition

### ISSUE THREAD

**Issue by Angelk90** [react-native-community/react-native-camera#2092] opened 2019-02-04 00:22 UTC
Hi @n1ru4l:

How can I make sure that I can save the picture with the square of the face recognition?

I would like to make sure that when the user takes the picture, and in the photo are recognized faces, as seen in the image. The photo is saved with a detail, ie the square that is used for facial facial recognition, for example.

Link expo: https://snack.expo.io/HJzPls-EV

![](https://camo.githubusercontent.com/630a13d530d3b7385f4127d4b74ac0b2adef466d/68747470733a2f2f692e696d6775722e636f6d2f35717a6d6b6c562e6a7067)

**Comment by n1ru4l** [comment] 2019-02-04 10:33
Duplicate of https://github.com/react-native-community/react-native-camera/issues/2035

**Closed by n1ru4l** 2019-02-04 10:33 UTC
