### ISSUE TITLE
Face detection not working on iOS 12.1.2, iPhone 6S

### ISSUE THREAD

**Issue by telmen** [react-native-community/react-native-camera#2033] opened 2019-01-04 03:43 UTC
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**

RNCamera
FaceDetector

**Platforms**

iOS

**Versions**

<! -- - Android: -->
- iOS: 12.1.2
- react-native-camera: ^1.6.4
- react-native: 0.57.7
- react: 16.6.1

**Description/Current Behaviour**

iPhone 6S(iOS 12.1.2) is currently not detecting any faces. On a component mount, facedetection callback called once with empty 
```js
{ 
  faces: []
  target: 175
  type: "face"
}
```
array and never called again. But on iPhone X(iOS 12.1), it's working strangely. 🤷‍♂️

**Expected Behaviour**

Face detection should work on iPhone 6S

**Steps to Reproduce**

Install the package using CocoaPods and run on a device, try to detect faces.

**Additionals**

Related issue #1870 and it's still open.

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by n1ru4l** [comment] 2019-01-04 15:12
Duplicate of #1870

**Closed by n1ru4l** 2019-01-04 15:12 UTC
Labels: Bug, Help Wanted, iOS
