### ISSUE TITLE
(Android) Auto-focus doesn't work on back camera

### ISSUE THREAD

**Issue by unipheye** [react-native-community/react-native-camera#432] opened 2016-09-28 12:19 UTC
### Expected behaviour

I expect the back camera to auto-focus for a sharp view.
### Actual behaviour

I have created a simple React Native app with react-native-camera just for testing. All works fine except the back camera doesn't auto-focus. I have tried to simplify the script just to be sure no settings are interfering but without any good result.
### Environment
- **Node.js version**: 5.10.1
- **React Native version**: 0.34.0
- **React Native platform + platform version**: Android 5.1.1
### react-native-camera

**Version**: npm
### Script

``` javascript

import React from 'react';
import {
  Image,
  StatusBar,
  StyleSheet,
  TouchableOpacity,
  View,
  TouchableHighlight,
  Text
} from 'react-native';
import Camera from 'react-native-camera';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  preview: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  overlay: {
    position: 'absolute',
    padding: 16,
    right: 0,
    left: 0,
    alignItems: 'center',
  },
  topOverlay: {
    top: 0,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bottomOverlay: {
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureButton: {
    padding: 15,
    backgroundColor: 'white',
    borderRadius: 40,
  },
  typeButton: {
    padding: 5,
  },
  flashButton: {
    padding: 5,
  },
  buttonsSpace: {
    width: 10,
  },
  Btn: {
    padding:20,
    backgroundColor:'blue'
  },
});

export default class CameraNew extends React.Component {
  constructor(props) {
    super(props);

    this.camera = null;

    this.state = {
      camera: {
        aspect: Camera.constants.Aspect.fill,
        captureTarget: Camera.constants.CaptureTarget.cameraRoll,
        type: Camera.constants.Type.back,
        orientation: Camera.constants.Orientation.auto,
        flashMode: Camera.constants.FlashMode.auto,
      },
      isRecording: false
    };

    this.takePicture = this.takePicture.bind(this);
    this.startRecording = this.startRecording.bind(this);
    this.stopRecording = this.stopRecording.bind(this);
    this.switchType = this.switchType.bind(this);
    this.switchFlash = this.switchFlash.bind(this);
  }

  takePicture() {
    if (this.camera) {
      this.camera.capture()
        .then((data) => console.log(data))
        .catch(err => console.error(err));
    }
  }

  startRecording() {
    if (this.camera) {
      this.camera.capture({mode: Camera.constants.CaptureMode.video})
          .then((data) => console.log(data))
          .catch(err => console.error(err));
      this.setState({
        isRecording: true
      });
    }
  }

  stopRecording() {
    if (this.camera) {
      this.camera.stopCapture();
      this.setState({
        isRecording: false
      });
    }
  }

  switchType() {
    let newType;
    const { back, front } = Camera.constants.Type;

    if (this.state.camera.type === back) {
      newType = front;
    } else if (this.state.camera.type === front) {
      newType = back;
    }

    this.setState({
      camera: {
        ...this.state.camera,
        type: newType,
      },
    });
  }

  get typeIcon() {
    let icon;
    const { back, front } = Camera.constants.Type;

    if (this.state.camera.type === back) {
      icon = require('./assets/ic_camera_rear_white.png');
    } else if (this.state.camera.type === front) {
      icon = require('./assets/ic_camera_front_white.png');
    }

    return icon;
  }

  switchFlash() {
    let newFlashMode;
    const { auto, on, off } = Camera.constants.FlashMode;

    if (this.state.camera.flashMode === auto) {
      newFlashMode = on;
    } else if (this.state.camera.flashMode === on) {
      newFlashMode = off;
    } else if (this.state.camera.flashMode === off) {
      newFlashMode = auto;
    }

    this.setState({
      camera: {
        ...this.state.camera,
        flashMode: newFlashMode,
      },
    });
  }

  _navigate(view) {
    this.props.navigator.resetTo({
      name: view, // Matches route.name
    })
  }

  get flashIcon() {
    let icon;
    const { auto, on, off } = Camera.constants.FlashMode;

    if (this.state.camera.flashMode === auto) {
      icon = require('./assets/ic_flash_auto_white.png');
    } else if (this.state.camera.flashMode === on) {
      icon = require('./assets/ic_flash_on_white.png');
    } else if (this.state.camera.flashMode === off) {
      icon = require('./assets/ic_flash_off_white.png');
    }

    return icon;
  }

  render() {
    return (
      <View style={styles.container}>
        <StatusBar
          animated
          hidden
        />
        <TouchableHighlight onPress={ () => this._navigate('Home') } style={  styles.Btn }>
          <Text>Go to camera</Text>
        </TouchableHighlight>
        <Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          style={styles.preview}
          aspect={this.state.camera.aspect}
          captureTarget={this.state.camera.captureTarget}
          type={this.state.camera.type}
          flashMode={this.state.camera.flashMode}
          defaultTouchToFocus
          mirrorImage={false}
        />
        <View style={[styles.overlay, styles.topOverlay]}>
          <TouchableOpacity
            style={styles.typeButton}
            onPress={this.switchType}
          >
            <Image
              source={this.typeIcon}
            />
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.flashButton}
            onPress={this.switchFlash}
          >
            <Image
              source={this.flashIcon}
            />
          </TouchableOpacity>
        </View>
        <View style={[styles.overlay, styles.bottomOverlay]}>
          {
            !this.state.isRecording
            &&
            <TouchableOpacity
                style={styles.captureButton}
                onPress={this.takePicture}
            >
              <Image
                  source={require('./assets/ic_photo_camera_36pt.png')}
              />
            </TouchableOpacity>
            ||
            null
          }
          <View style={styles.buttonsSpace} />
          {
              !this.state.isRecording
              &&
              <TouchableOpacity
                  style={styles.captureButton}
                  onPress={this.startRecording}
              >
                <Image
                    source={require('./assets/ic_videocam_36pt.png')}
                />
              </TouchableOpacity>
              ||
              <TouchableOpacity
                  style={styles.captureButton}
                  onPress={this.stopRecording}
              >
                <Image
                    source={require('./assets/ic_stop_36pt.png')}
                />
              </TouchableOpacity>
          }
        </View>
      </View>
    );
  }
}


```

**Comment by andrerfneves** [comment] 2016-09-28 19:03
Pretty sure you have to implement these two methods:
https://github.com/lwansbrough/react-native-camera#onfocuschanged-event--nativeevent--touchpoint--x-y--

Like so:

```
_handleFocusChanged() { /***/ }
_handleZoomChanged() { /***/ }
```

And then make sure you have these props in your Camera component:

```
defaultOnFocusComponent
onFocusChanged={this._handleFocusChanged}
onZoomChanged={this._handleZoomChanged}
```

**Comment by unipheye** [comment] 2016-09-28 19:18
Hi @andrerfneves, I tried that but still nothing seems to happen. Tap-to-focus also doesn't work either. The view stays in the same focus area and doesn't adjust.

**Comment by harshq** [comment] 2016-11-02 10:48
Any luck with this ? Im having the same issue :/

**Comment by kenmaca** [comment] 2016-12-04 02:13
Also having the same issue here. iOS `onFocusChanged` works as intended.

**Comment by abrahambotros** [comment] 2017-01-30 06:05
Hi all, please check out https://github.com/lwansbrough/react-native-camera/pull/575 for tap-to-focus and improved (continuous) auto-focus. I've also noted in the README that indeed `onFocusChanged` and `onZoomChanged` don't actually get called on Android yet, though pinch-to-zoom seems to work (without any of my PR changes) and https://github.com/lwansbrough/react-native-camera/pull/575 should enable tap-to-focus and better auto-focus as you guys have been mentioning.

**Comment by ospfranco** [comment] 2018-01-12 21:09
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

**Closed by ospfranco** 2018-01-12 21:09 UTC
