### ISSUE TITLE
Bad Camera Ref -> no preview, can't access camera class

### ISSUE THREAD

**Issue by twalk4821** [react-native-community/react-native-camera#2072] opened 2019-01-26 19:11 UTC
# Bug Report
**To Do First**
- [x] Did you try latest release? yes
- [x] Did you try master? yes
- [x] Did you look for existing matching issues? yes

**Related Modules**
RNCamera

**Platforms**
Android

**Versions**

- Android: 26-27
- react-native-camera: 1.8.1 and 1.9
- react-native: 0.57.8
- react: 16.6.3

**Description/Current Behaviour**
Preview loads black. When trying to log out the "ref" to camera component, whole app freezes up. Not even null... just hangs up. Can't load preview, can't access camera class. 

**Steps to Reproduce**
Boilerplate camera code: 
```
export default class Cam extends React.Component {
  takePicture = async function() {
    if (this.camera) {
      this.camera.stopPreview()
      console.log('???')
      console.log('camera: ',this.camera) // don't see this line printed
      const options = { quality: 0.5, base64: true };
      const data = await this.camera.takePictureAsync(options);
      const image = data.uri
   
    }
  };

  render() {
    return (
      <View style={styles.container}>
        <RNCamera
          ref={ref => {
            console.log(ref)
            this.camera = ref;
          }}
          style={styles.preview}
          type={RNCamera.Constants.Type.back}
          flashMode={RNCamera.Constants.FlashMode.off}
          captureAudio={false}
        />
        <View style={{ flex: 0, flexDirection: 'row', justifyContent: 'center' }}>
          <TouchableOpacity onPress={this.takePicture.bind(this)} style={styles.capture}>
            <Text style={{ fontSize: 14 }}> SNAP </Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }
}
```

**Comment by n1ru4l** [comment] 2019-01-28 08:12
Logging the camera object can freeze the thread and as a result crash your application, you should avoid it.

**Comment by twalk4821** [comment] 2019-01-29 04:16
Hi - 

Thanks for the suggestion. Just removed all the logging statements. Now I'm back to the original error (which I should have posted, as well):

```
 Error: takePictureAsync: Expected a Camera component
```
Let me know if there's any other information I can provide you. 
Thanks - 
Tyler

**Comment by n1ru4l** [comment] 2019-01-30 08:03
duplicate of #1931

**Closed by n1ru4l** 2019-01-30 08:03 UTC
Labels: Android, Needs response from author
