### ISSUE TITLE
Undefined is not an object (evaluating CameraManager.Aspect)

### ISSUE THREAD

**Issue by tomderudderetna** [react-native-community/react-native-camera#2088] opened 2019-02-02 18:20 UTC
# Bug Report
**To Do First**
- [ ] Did you try latest release?
- [ ] Did you try master?
- [ ] Did you look for existing matching issues?

**Related Modules**

**Platforms**

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:

**Description/Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**
![photo_2019-02-02_19-13-41](https://user-images.githubusercontent.com/30437729/52167681-32b98800-271f-11e9-91f9-a7dab8222df1.jpg)

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by n1ru4l** [comment] 2019-02-03 19:30
Please try to link the project properly with `react-native link` (or manually depending on your setup). Please also keep in mind, that this project could also have conflicts when using the expo SDK.

**Comment by tomderudderetna** [comment] 2019-02-07 07:28
Your example don t work, I have no choice to use Expo beacause create-react-app is is not up to date

**Comment by n1ru4l** [comment] 2019-02-07 07:32
What exactly is wrong with the example app?it works fine for me.

Please provide a reproduction repository.

**Comment by SimonErm** [comment] 2019-02-13 23:22
The stacktrace leads to Camera.js which relates to RCTCamera. Am I right? If i am right try RNCamera, because RCTCamera is deprecated.

**Comment by n1ru4l** [comment] 2019-02-15 11:56
Closing this issue since there is no feedback from the author. If anyone still experiences this issue with the latest version of react-native-camera and `RNCamera` he should open a new issue.

**Closed by n1ru4l** 2019-02-15 11:56 UTC
Labels: Android, Needs more information, Needs response from author
