### ISSUE TITLE
Camera run always (Display off, in Background etc)

### ISSUE THREAD

**Issue by fasibio** [react-native-community/react-native-camera#556] opened 2017-01-16 15:06 UTC
### Steps to reproduce
Buid a app with this code in renderer
 ```
<Camera
        ref="cam"
        barCodeTypes={['ean13']}
        onBarCodeRead={(data,bounds ) =>{
          console.log('read',data, bounds)
        }}
        aspect={Camera.constants.Aspect.fill}
        style={styles.preview}
        flashMode={Camera.constants.FlashMode.on}
        />
```
Start react-native log-android 
Take off the display. 
Scan an ean-13 barcode. 
You can see a output in the log

You have to override the Lifecycle Methods... 

### Environment
- React native : 0.40.0:
- Platform Nexus 6P Android 7.1.1

### react-native-camera
"react-native-camera": "^1.0.0-alpha1"

**Comment by juanluisgv1** [comment] 2017-01-25 17:48
I had the same issue, have you unmounted the component which renders the camera?

**Comment by carleryd** [comment] 2017-01-26 09:59
I have had this issue for a long time and solved it as @juanluisgv1 suggests. This however makes switching from an to the camera view really slow.
Comparing a Nexus 5x device using this "hack" it takes over 1000ms to switch to and from the camera view, while an iPhone 5s doesn't need this hack and switches between camera and other view in about 50ms.
It seems that on iPhone, it switches to the camera view, and is initially black until the native camera has loaded. I would like to have the same behavior on Android

**Comment by wenwen1995** [comment] 2017-08-21 02:49
I  think  @carleryd  idea is a good solution,and I find another solution to solve this problem,Please look at this link:[https://www.thepolyglotdeveloper.com/2015/10/implement-a-barcode-scanner-using-react-native/](url),
it may set a flag as true in initial  to render the camera, if the flag equals false, return null...When the onBarCodeRead function works,it sets the flag false.That's will prevent the Camera always works.

`this.state = { barCodeFlag : true}`

` render() {
    return (
    	<View style={_styles.container}>
         {  this.renderCamera()  }
        </View>
    	)
    }`

`  renderCamera() {
       let { barCodeFlag } = this.state;
        if(barCodeFlag ) {
            return (
                <Camera
                    ref="cam"
                    style={styles.container}
                    onBarCodeRead={this.onBarCodeRead.bind(this)}
                    type={this.state.cameraType}>
                </Camera>
            );
        } else {
            return  null;
        }
    },`

`onBarCodeRead(e){
      this.setState({barCodeFlag: false}); 
      Vibration.vibrate(); //扫码震动
     console.log('e.data=>',e.data);
}
`

**Comment by galhardi** [comment] 2017-09-09 11:44
@wenwen1995, how can I enable the camera again?

**Comment by wenwen1995** [comment] 2017-09-09 14:40
I don't understand your thoughts...You main like this?First time the  camera reads a code data,and prints it,and next time,you want the camera to reads another code data,and prints this data again?

**Comment by galhardi** [comment] 2017-09-09 15:52
I need enable cam when navigate (using tab navigation) to a screen and disable when navigate to another screen.
In my case when I read code and redirect to another screen my can continue activate and read another codes.
Thks for your response.

**Comment by milon87** [comment] 2017-09-10 19:15
when it reads a code then  navigate to another acreen. Camera is still reading in the background!!!! If I stop reading then how to enable again when user backs to the camera screen ?

**Comment by galhardi** [comment] 2017-09-10 19:22
@milon87 exactly!

**Comment by wenwen1995** [comment] 2017-09-11 00:53
@galhardi ,may be you should use ** this.props.navigator.replace** to jump another screen,and this  will destory the current pages,so it can stop the camera working....Also,I think you should focus my first answer of this problem ,please set a flag as true in initially,when page  renders, it will start the camera, and when the onBarCodeRead function works,it sets the flag false.And you can jump another page after this.That's will prevent the Camera always works.

**Comment by galhardi** [comment] 2017-09-11 01:40
@wenwen1995, I tried use the flag. I set true on componentWillMount and false on  onBarCodeRead. But when I come back to camera page the componentWillMount not trigger again.
 How can I set true the flag again?
Thanks for your help.

**Comment by wenwen1995** [comment] 2017-09-11 02:05
![7](https://user-images.githubusercontent.com/12100065/30255770-83b5fafa-96d8-11e7-8b50-7589c3879b3e.png)

I set flag true in initially,and this will be okay,not set it in the componentWillMount function,just have a try

**Comment by galhardi** [comment] 2017-09-11 02:43
@wenwen1995, I'm tried use constructor but it's called just in the first time that I enter on camera page.
I'm using react-navigation (TabNavigator), I don't know if this is the cause of my problem.

**Comment by wenwen1995** [comment] 2017-09-11 03:43
@galhardi ,oh I think it may be the react-navigation problem,when it backs to camera page,it doesn't trigger the render,So I think there is a way to solve it.---->You can jump  camera page 
with return parameters(about this ,you should search react-navigation about how to back a page with return parameters...  ),it will trigger the page render again,

**Comment by ospfranco** [comment] 2018-01-13 12:42
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

P.S. There is a new implementation of the camera on android RNCamera, it is on the master branch, you can try it and see if it fixes your problem

**Closed by ospfranco** 2018-01-13 12:42 UTC

**Comment by exhesham** [comment] 2018-02-05 20:58
the answer is to put it in a state and then set that state to null - worked for me
