### ISSUE TITLE
App crashed / App reload when changing the permission of camera

### ISSUE THREAD

**Issue by keung725** [react-native-community/react-native-camera#403] opened 2016-09-12 15:56 UTC
### Steps to reproduce

App reload:
1. Go to setting, close camera permission, run app
2. Go to camera component
3. Go to setting, open permission
4. App reload

App crashed:
1. Go to camera component
2. Go to setting, close permission
3. App crashed

I don't want App reload and App crashed any more.
How can I handle it with not modifying the objective-c, because I don't know it. Thanks.

**Comment by ryankask** [comment] 2016-09-13 06:58
I think this is expected behaviour as iOS kills apps when privacy permissions change.

**Comment by smartt** [comment] 2016-09-15 14:11
FWIW, I'm running into an app crash as well, but it seems to just be on iOS 10.  I added https://github.com/yonahforst/react-native-permissions to help detect the permissions; but at this point, even with permission granted, it's still crashing even if I just import `react-native-camera`.

**Comment by pranny** [comment] 2016-09-15 18:48
Starting iOS 10, the key `NSCameraUsageDescription` is mandatory in `Info.plist`. Quoting from the [apple developer documentation](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html)

>To protect user privacy, an iOS app linked on or after iOS 10.0, and which accesses the device’s camera, must statically declare the intent to do so. Include the NSCameraUsageDescription key in your app’s Info.plist file and provide a purpose string for this key. If your app attempts to access the device’s camera without a corresponding purpose string, your app exits.

I also faced app crash issues and updating `Info.plist` resolved it. Give it a try.

**Comment by smartt** [comment] 2016-09-15 19:48
An update on the crash we're having:

We do have `NSCameraUsageDescription` defined (that was caught on a Test Flight upload) as well as `NSPhotoLibraryUsageDescription`.

When running in Test-mode, XCode's debugger halts in `RCTCameraManager.m`, line 33, with a `EXC_BAD_ACCESS (code=1, address=0x50)`.  Currently, line 33 reads:

```
self.previewLayer = [AVCaptureVideoPreviewLayer layerWithSession:self.session];
```

Any ideas?

**Comment by keung725** [comment] 2016-09-16 06:02
same here

**Comment by rgoldiez** [comment] 2016-09-17 16:13
Wasn't happening to me on iPhone 6s w/ iOS (actual device) ....... but iPhone 7 w/ iOS 10 is crashing now in the same way as described earlier in this thread.

**Comment by krzkaczor** [comment] 2016-09-19 20:22
Here's a full bug report and more solutions: https://github.com/lwansbrough/react-native-camera/issues/386

**Comment by xavicolomer** [comment] 2016-09-22 16:41
For me it crashed until I set all Pricacy Settings:

- NSCameraUsageDescription

**Comment by comountainclimber** [comment] 2016-09-26 19:51
experiencing the same issue... :(

**Comment by JimmyStavros** [comment] 2016-11-16 05:54
@smartt hey not sure if you got this working but try nitrog7's solution in #386. Worked like a charm for me.

**Comment by KarthickHero** [comment] 2017-10-12 10:38
I just added exit(0) when i opened the camera settings. It's working fine

**Comment by victorbadila** [comment] 2017-11-03 09:27
@KarthickHero where did you add that one line and for what purpose? Could you give more details?

The issue happens for me on iOS11 on both iPhone 7 and iPhone SE, however it seems to be a general permissions problem, happens when I change permissions for anything, I don't think it is a react-native-camera specific problem.

**Comment by MIFind** [comment] 2017-12-21 09:42
Hey , I have a problem.
Do i still need `react-native-permissions` for private permission , the time when I have seted
`NSCameraUsageDescription
NSMicrophoneUsageDescription`.

**Comment by mchandleraz** [comment] 2018-01-02 04:34
@MIFind I don't quite understand your question, but I recently implemented permissions checking in my app using the `checkVideoAuthorizationStatus` and `checkDeviceAuthorizationStatus`. These methods return a Boolean indicating whether you have the permissions. Check README.md for more info.

**Comment by ospfranco** [comment] 2018-01-12 21:07
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

**Closed by ospfranco** 2018-01-12 21:07 UTC
