### ISSUE TITLE
OutOfMemoryError when rotating image

### ISSUE THREAD

**Issue by bhaskarmurthy** [react-native-community/react-native-camera#795] opened 2017-07-19 18:10 UTC
I'm seeing a crash when creating the bitmap during a rotation - on Android

Stacktrace is attached below:

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 31961100 byte allocation with 16777216 free bytes and 26MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:720)
       at com.lwansbrough.RCTCamera.RCTCameraModule.rotate(RCTCameraModule.java:562)
       at com.lwansbrough.RCTCamera.RCTCameraModule.fixOrientation(RCTCameraModule.java:581)
       at com.lwansbrough.RCTCamera.RCTCameraModule.access$300(RCTCameraModule.java:45)
       at com.lwansbrough.RCTCamera.RCTCameraModule$3.onPictureTaken(RCTCameraModule.java:673)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1223)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by skovhus** [comment] 2017-08-18 22:09
Duplicate of https://github.com/lwansbrough/react-native-camera/issues/590

**Closed** 2018-09-25 00:03 UTC
