### ISSUE TITLE
iOS Facial Detection Currently Broken (iOS 12)

### ISSUE THREAD

**Issue by jbwhitcombe** [react-native-community/react-native-camera#1861] opened 2018-10-17 01:51 UTC
# Bug Report
**To Do First**
- Tried latest release
- Tried master
- There are existing reports however they are all closed

**Related Module**
FaceDetector

**Platform**
iOS

**Description/Current Behaviour**
Currently crashing with iOS 12 with an EXC_BAD_ACCESS when onFacesDetected function is called. Potentially due to onFacesDetected being called even when no faces are available to be detected (the function is being called on instantiation of the RNCamera object).

**Expected Behaviour**
Should not cause a crash. This bug has rendered the library unusable for facial recognition on iOS.

**Steps to Reproduce**
On an iPad 10.5 model, instantiating an RNCamera view and supplying a function for OnFacesDetected causes a crash immediately with the following error appearing in Xcode.

![image](https://user-images.githubusercontent.com/28974101/47057168-43df9700-d20b-11e8-9ce9-8e9cc15f75de.png)

**Comment by jgfidelis** [comment] 2018-10-18 00:32
There was an issue where people identified what line code broke the facial recognition. Do you know enough objective C to try and fix it?

**Comment by jbwhitcombe** [comment] 2018-10-18 02:07
Perhaps! My Objective-C > Swift, although any direction on what line is causing this would help!

**Comment by n1ru4l** [comment] 2018-10-18 12:56
duplicate of https://github.com/react-native-community/react-native-camera/issues/1613

**Closed by n1ru4l** 2018-10-18 12:56 UTC
Labels: Bug, iOS

**Comment by imspikey** [comment] 2018-10-18 14:15
yes but  #1613  is closed without solution?!!!

**Comment by jbwhitcombe** [comment] 2018-10-22 23:59
@n1ru4l Yep. This resolves this issue for sure, thanks heaps! Interestingly, I had to reinstall everything via Pods as manual installation of the GMV didn't work. Perhaps it's worth adding this as part of the installation process for the latest version and with iOS 12 now?
