### ISSUE TITLE
Face recorgnition

### ISSUE THREAD

**Issue by shohailahm** [react-native-community/react-native-camera#1962] opened 2018-12-02 17:11 UTC
# Question

**To Do First**
- [ ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

Onfaces detected is getting called when faces comes infront of camera but doesnt fire event when the faces go out of camera?

**Comment by n1ru4l** [comment] 2018-12-02 20:30
Duplicate of #1963

**Closed by n1ru4l** 2018-12-02 20:30 UTC
