### ISSUE TITLE
Takes a lot of time to take/show and store image

### ISSUE THREAD

**Issue by bvv218** [react-native-community/react-native-camera#1000] opened 2017-11-22 07:58 UTC
It takes 3-4 sec to show photo after taking it and 6-8 sec to store it. I am using the example and it's the same. Is there a way to increase the speed?

**Comment by stianjensen** [comment] 2017-11-22 11:22
Is this on android? In that case this is a duplicate of #768

**Comment by bvv218** [comment] 2017-11-23 01:34
@stianjensen Yes, it's on android, not tested on ios. #768 says that delay is only to store image (I have had this before as well), but now I started to have the delay between taking the picture and showing the preview too. Is there a way to fix at least this part of the problem?

**Comment by stianjensen** [comment] 2017-11-23 08:46
Not that I’m aware of. I have the same problem wherre even the preview is slow to show up.

**Comment by KS-Balaji** [comment] 2017-11-23 14:10
I have exactly the same problem... any solutions...?

**Comment by ducpt2** [comment] 2017-12-01 09:23
+ 1. same problem...

**Comment by MehdiAlouafi** [comment] 2017-12-05 16:46
+ 1

**Comment by EladAvni** [comment] 2017-12-28 09:41
+1

**Comment by AlexandreMaistret** [comment] 2018-01-09 19:26
+1 Did someone have find any solution ?  Because it is really too slow and I have tried on two smartphones Wiko and Samsung, and the two are really really slow when a photo is taken.

**Comment by VrajSolanki** [comment] 2018-02-21 10:43
+1

**Comment by JohnRyanTsai** [comment] 2018-02-26 02:03
+1

**Comment by ospfranco** [comment] 2018-04-03 13:35
added skipProcessing flag (android only) for the takePictureAsync call params, this should make picture snapping super fast, but might break rotation on some of your apps.

Please give it a go on the master branch.

**Closed** 2018-04-03 14:36 UTC

**Comment by andreh111** [comment] 2018-05-05 06:28
hey guys try using this https://www.npmjs.com/package/react-native-fast-image 
it can solve the problem of image loading time

**Comment by lucasluca** [comment] 2020-02-06 15:59
i was using this config:
const options = { quality: 0.1, base64: false, forceUpOrientation: true, fixOrientation: true, skipProcessing: true };

and then i removed {forceUpOrientation: true, fixOrientation: true}, from this object and got it working really fast

**Comment by devartwa** [comment] 2020-12-04 17:44
i removed fixOrientation: false and worked for me.
