### ISSUE TITLE
There is a conflict with  react-native-firebase

### ISSUE THREAD

**Issue by lizhuoyuan** [react-native-community/react-native-camera#1711] opened 2018-07-27 08:27 UTC
package.json:
    "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera"

then i run yarn install and react-native-link react-native-camera. 
these successd.
in the android , build fail：
All firebase libraries must be either above or below 14.0.0

**Comment by jgcmarins** [comment] 2018-07-27 11:30
> All firebase libraries must be either above or below 14.0.0
I think this is related to your project's `build.gradle`

**Comment by tonmanayo** [comment] 2018-07-29 12:17
I'm having the same issue, can't use react-native-firebase with react-native-camera,

Error: 
Failed to capture snapshot of input files for task ':react-native-camera:compileDebugAidl' property 'importDirs' during up-to-date check.
> The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 12.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

package.json: 

{
  "name": "pushNotif",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "apisauce": "^0.15.2",
    "format-json": "^1.0.3",
    "lodash": "^4.17.10",
    "md5": "^2.2.1",
    "moment": "^2.22.2",
    "native-base": "^2.7.2",
    "prop-types": "^15.6.2",
    "querystringify": "^2.0.0",
    "ramda": "^0.25.0",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-awesome-card-io": "^0.7.0",
    "react-native-camera": "^1.1.4",
    "react-native-firebase": "^4.3.8",
    "react-native-push-notification": "^3.0.2"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "^5",
    "jest": "23.4.1",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

Anyone know how I can get around this?

**Comment by lizhuoyuan** [comment] 2018-07-30 02:31
@tonmanayo  maybe you should use react-native-image-picker

**Comment by tonmanayo** [comment] 2018-07-30 04:43
@lizhuoyuan I need the camera to scan barcodes

**Comment by lizhuoyuan** [comment] 2018-08-09 03:05
@banaszeknorbert  thanks! I will try

**Comment by lizhuoyuan** [comment] 2018-08-09 03:09
@banaszeknorbert  love you haha , it was solved

**Comment by erez-guesty** [comment] 2018-08-13 13:48
@banaszeknorbert 
where is the 'ext' section? i dont have it in the build.gradle...
can you post your file?
thanks

**Comment by tonmanayo** [comment] 2018-08-13 14:44
buildscript {
     repositories {
         google()
         jcenter()
     }
     dependencies {
         classpath 'com.android.tools.build:gradle:3.1.3'
         classpath 'com.google.gms:google-services:4.0.1'
     }
 }

 allprojects {
     repositories {
         mavenLocal()
         google()
         jcenter()
         maven {
             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
             url "$rootDir/../node_modules/react-native/android"
         }
         maven { url "https://jitpack.io" }
     }
 }

 ext {
     buildToolsVersion = "26.0.2"
     minSdkVersion = 16
     compileSdkVersion = 26
     targetSdkVersion = 25
     supportLibVersion = "26.1.0"
 }

This is how my top level build.gradle file looks and everything is working perfectly now.


your other build.gradle file should look something like this: 
apply plugin: "com.android.application"
import com.android.build.OutputFile
project.ext.react = [
    entryFile: "index.js"
]
apply from: "../../node_modules/react-native/react.gradle"
def enableSeparateBuildPerCPUArchitecture = false
def enableProguardInReleaseBuilds = false
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.yourAppName"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-vector-icons')
    compile project(':react-native-svg')
    compile project(':react-native-i18n')
    compile project(':react-native-config')
    compile project(':react-native-camera')
    compile project(':react-native-push-notification')
    implementation project(':react-native-firebase')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "com.google.firebase:firebase-core:16.0.1"
    implementation 'com.google.firebase:firebase-messaging:+'
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
}
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply plugin: 'com.google.gms.google-services'
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

gradle wrapper properties file: distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

**Comment by hggz** [comment] 2019-01-17 07:56
There isn't a conflict my son. I'm going to say this one time, and one time only.

CLEAN your mother ****ing grade build cache.

./gradlew cleanBuildCache

**Comment by n1ru4l** [comment] 2019-01-17 08:59
@hggz Please watch your language 😇

Duplicate of #2043

**Closed by n1ru4l** 2019-01-17 08:59 UTC
